"""
PHASE 0 - Data Quality Assessment.
Computes structural + quality metrics for both datasets and writes:
  - outputs/reports/phase0_data_quality.md   (human readable)
  - outputs/reports/phase0_metrics.json      (machine readable, reused later)
Does NOT correct data; only measures and flags.
"""
import os
import json
import numpy as np
import pandas as pd
from load_data import all_storage, all_outbound, combined_outbound

OUT = os.path.join(os.path.dirname(__file__), "..", "outputs", "reports")
os.makedirs(OUT, exist_ok=True)

metrics = {"storage": {}, "outbound": {}, "cross": {}}
lines = []


def w(s=""):
    lines.append(s)


w("# PHASE 0 - DATA QUALITY ASSESSMENT")
w("Site: DHL Supply Chain, Bemmel (WH NL_0032) | Operation: Assa Abloy (CID003739NL)")
w("Auto-generated by analysis/data_quality.py. No values were altered.\n")

# ============================ STORAGE =====================================
w("## 1. STORAGE / INVENTORY SNAPSHOTS\n")
storage = all_storage()
w("| File | Snapshot date | Records | Unique DTLNUM | Unique PART | Unique LOCATION | Unique LODNUM |")
w("|---|---|--:|--:|--:|--:|--:|")
for fn, df in storage.items():
    snap = pd.to_datetime(df["DATE"], errors="coerce").dropna()
    snap_d = snap.dt.date.mode().iat[0] if len(snap) else "?"
    m = {
        "records": int(len(df)),
        "snapshot_date": str(snap_d),
        "unique_dtlnum": int(df["DTLNUM"].nunique()),
        "unique_part": int(df["PART"].nunique()),
        "unique_location": int(df["LOCATION"].nunique()),
        "unique_lodnum": int(df["LODNUM"].nunique()),
        "total_qty_eaches": float(pd.to_numeric(df["QTY"], errors="coerce").sum()),
        "dtlnum_duplicated": int(df["DTLNUM"].duplicated().sum()),
        "qty_le_zero": int((pd.to_numeric(df["QTY"], errors="coerce") <= 0).sum()),
        "loc_type_counts": df["LOC TYPE"].value_counts().to_dict(),
        "part_abccod_counts": df["PART ABCCOD"].value_counts().to_dict(),
        "hazmat_counts": df["HAZMAT"].astype(str).value_counts().to_dict(),
        "asset_type_counts": df["ASSET TYPE"].astype(str).value_counts().head(10).to_dict(),
        "area_counts": df["AREA"].value_counts().to_dict(),
    }
    metrics["storage"][fn] = m
    w(f"| {fn} | {m['snapshot_date']} | {m['records']:,} | {m['unique_dtlnum']:,} | "
      f"{m['unique_part']:,} | {m['unique_location']:,} | {m['unique_lodnum']:,} |")

# use latest snapshot for detailed quality view
latest_fn = sorted(storage.keys())[-1]
sdf = storage[latest_fn]
w(f"\n**Detailed quality checks on latest snapshot ({latest_fn}):**\n")

pa_qty = pd.to_numeric(sdf["PA QTY"], errors="coerce")
qty = pd.to_numeric(sdf["QTY"], errors="coerce")
checks = {
    "Records": len(sdf),
    "Duplicate DTLNUM (should be 0)": int(sdf["DTLNUM"].duplicated().sum()),
    "QTY missing": int(qty.isna().sum()),
    "QTY <= 0": int((qty <= 0).sum()),
    "PA QTY missing": int(pa_qty.isna().sum()),
    "PA WGT missing": int(pd.to_numeric(sdf["PA WGT"], errors="coerce").isna().sum()),
    "CS QTY missing (each-pick SKUs w/o case)": int(pd.to_numeric(sdf["CS QTY"], errors="coerce").isna().sum()),
    "PART VELOCITY missing": int(sdf["PART VELOCITY"].isna().sum()),
    "AISLE/ZONE missing (loose/staging?)": int(sdf["AISLE"].isna().sum()),
    "EA dims present": int(pd.to_numeric(sdf["EA LEN"], errors="coerce").notna().sum()),
}
w("| Check | Value |")
w("|---|--:|")
for k, v in checks.items():
    w(f"| {k} | {v:,} |")
metrics["storage"]["_latest_checks"] = {k: int(v) for k, v in checks.items()}
metrics["storage"]["_latest_file"] = latest_fn

w("\n**LOC TYPE distribution (latest):** " +
  ", ".join(f"{k}={v}" for k, v in sdf["LOC TYPE"].value_counts().items()))
w("\n**PART ABCCOD distribution (latest):** " +
  ", ".join(f"{k}={v}" for k, v in sdf["PART ABCCOD"].value_counts().items()))
w("\n**AREA distribution (latest):** " +
  ", ".join(f"{k}={v}" for k, v in sdf["AREA"].value_counts().items()))
w("\n**ASSET TYPE (pallet type) distribution (latest):** " +
  ", ".join(f"{k}={v}" for k, v in sdf["ASSET TYPE"].astype(str).value_counts().head(8).items()))

# ============================ OUTBOUND ====================================
w("\n## 2. OUTBOUND / SHIPPING+PICKING TRANSACTIONS\n")
outbound = all_outbound()
w("| File | Rows(order lines) | Unique ORDER NO | Unique SHIPMENT | Unique PART | Unique SHIP-TO | Date span |")
w("|---|--:|--:|--:|--:|--:|---|")
for fn, df in outbound.items():
    d = pd.to_datetime(df["DATE"], errors="coerce")
    m = {
        "order_lines": int(len(df)),
        "unique_orders": int(df["ORDER NO"].nunique()),
        "unique_shipments": int(df["SHIPMENT ID"].nunique()),
        "unique_parts": int(df["PRTNUM"].nunique()),
        "unique_shipto": int(df["SHIP TO NAME"].nunique()),
        "unique_carriers": int(df["CARRIER NAME"].nunique()),
        "unique_countries": int(df["SHIP TO COUNTRY"].nunique()),
        "date_min": str(d.min().date()) if d.notna().any() else "?",
        "date_max": str(d.max().date()) if d.notna().any() else "?",
        "total_picked_qty": int(pd.to_numeric(df["PICKED QTY"], errors="coerce").sum()),
        "picked_qty_le0": int((pd.to_numeric(df["PICKED QTY"], errors="coerce") <= 0).sum()),
        "dup_order_line": int(df.duplicated(subset=["ORDER NO", "LINE"]).sum()),
        "staged_status_counts": df["STAGED STATUS"].value_counts().to_dict(),
        "order_type_counts": df["ORDER TYPE"].value_counts().to_dict(),
        "pick_date_missing": int(pd.to_datetime(df["PICK DATE"], errors="coerce").isna().sum()),
        "unit_price_missing": int(pd.to_numeric(df["UNIT PRICE"], errors="coerce").isna().sum()),
    }
    metrics["outbound"][fn] = m
    w(f"| {fn} | {m['order_lines']:,} | {m['unique_orders']:,} | {m['unique_shipments']:,} | "
      f"{m['unique_parts']:,} | {m['unique_shipto']:,} | {m['date_min']} -> {m['date_max']} |")

allob = combined_outbound()
allob["DATE"] = pd.to_datetime(allob["DATE"], errors="coerce")
allob["PICK DATE"] = pd.to_datetime(allob["PICK DATE"], errors="coerce")
allob["ORDER ARRIVE DATE"] = pd.to_datetime(allob["ORDER ARRIVE DATE"], errors="coerce")

# order-line grain sanity: is (ORDER NO, LINE) unique within a month? across all?
w("\n**Combined outbound (3 months):**\n")
comb = {
    "total_order_lines": int(len(allob)),
    "unique_orders_all": int(allob["ORDER NO"].nunique()),
    "unique_parts_all": int(allob["PRTNUM"].nunique()),
    "date_min": str(allob["DATE"].min().date()),
    "date_max": str(allob["DATE"].max().date()),
    "distinct_ship_days": int(allob["DATE"].dt.date.nunique()),
    "total_picked_qty": int(pd.to_numeric(allob["PICKED QTY"], errors="coerce").sum()),
    "pct_lines_single_unit": round(float((pd.to_numeric(allob["PICKED QTY"], errors="coerce") == 1).mean()) * 100, 1),
    "staged_LATE_pct": round(float((allob["STAGED STATUS"] == "LATE").mean()) * 100, 1),
}
metrics["cross"]["outbound_combined"] = comb
for k, v in comb.items():
    w(f"- {k}: {v}")

# lines per order distribution
lpo = allob.groupby(["SOURCE_FILE", "ORDER NO"]).size()
metrics["cross"]["lines_per_order"] = {
    "mean": round(float(lpo.mean()), 2),
    "median": float(lpo.median()),
    "p95": float(lpo.quantile(0.95)),
    "max": int(lpo.max()),
}
w(f"\n- Lines per order: mean={lpo.mean():.2f}, median={lpo.median():.0f}, "
  f"p95={lpo.quantile(0.95):.0f}, max={lpo.max():.0f}")

# daily shipped lines (throughput) - average vs peak
daily = allob.groupby(allob["DATE"].dt.date).size()
metrics["cross"]["daily_shipped_lines"] = {
    "mean": round(float(daily.mean()), 1),
    "median": float(daily.median()),
    "peak": int(daily.max()),
    "peak_day": str(daily.idxmax()),
    "peak_over_avg": round(float(daily.max() / daily.mean()), 2),
}
w(f"- Daily shipped order-lines: mean={daily.mean():.0f}, median={daily.median():.0f}, "
  f"PEAK={daily.max():.0f} on {daily.idxmax()} (peak/avg = {daily.max()/daily.mean():.2f}x)")

# pick lead time (order arrive -> pick)
lt = (allob["PICK DATE"] - allob["ORDER ARRIVE DATE"]).dt.total_seconds() / 3600.0
lt = lt[(lt > -1) & (lt < 24 * 30)]  # keep plausible window for stat only
metrics["cross"]["pick_leadtime_hours"] = {
    "median": round(float(lt.median()), 1),
    "mean": round(float(lt.mean()), 1),
    "p90": round(float(lt.quantile(0.90)), 1),
}
w(f"- Pick lead time (order arrive -> pick), plausible rows: median={lt.median():.1f}h, "
  f"p90={lt.quantile(0.90):.1f}h")

# ============================ SAVE ========================================
with open(os.path.join(OUT, "phase0_metrics.json"), "w", encoding="utf-8") as f:
    json.dump(metrics, f, indent=2, default=str)

with open(os.path.join(OUT, "phase0_data_quality.md"), "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print("\n".join(lines))
print("\n\n[written] outputs/reports/phase0_data_quality.md and phase0_metrics.json")
